name: Python KeyCloakClient Tests

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.5', '3.6', '3.7' ]
    name: Python ${{ matrix.python-version }} tests
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U pipenv
          pipenv install --dev
      - name: Flake8
        run: |
          pipenv run flake8 src/keycloak tests/keycloak
      - name: Test with pytest
        run: |
          pipenv run pytest